sudo: required
services:
  - docker

before_install:
  - docker build -t dieke102/docker-react -f Dockerfile.dev .

script:
  - docker run dieke102/docker-react npm run test -- --coverage

# tell travis how to take our application and deploy it to AWS
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-042413666034"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
